### ISSUE TITLE
403 When Trying to clone

### ISSUE THREAD

**Issue by edynas68** [phpish/shopify_app-skeleton#10]
Hi,

When I execute the line git clone --depth 1 --branch master https://github.com/phpish/shopify_app-skeleton.git new_prj I get a 403 error saying "The requested URL returned error: 403 Forbidden while accessing https://github.com/phpish/shopify_app_skeleton.git/info/refs"
Any idea what I am doing wrong? I will admit right away that I am not really used to github and thus it could easily be something I done. I have normall access to my server with PUTTY and was able to excecute other commands without any issue

Appreciate any help

Thanks,
Edwin

**Comment by myjanky** [comment]
@edynas68 

I tried cloning and did not get this error. What version of git do you have installed? 1.7 is Github's preferred version but any version should work. 
There may also be a routing problem on your end of the network but I digress. A 403 is a server message sent message. so I doubt it to be on your end/

**Comment by edynas68** [comment]
The version is 1.7.9.5 and I just tried again and it worked. My best guess...I just signed up at Github and I think my user/pass was not 100% working or something
