### ISSUE TITLE
Oauth error invalid_request: The redirect_uri is missing or not whitelisted 

### ISSUE THREAD

**Issue by Mike2100** [phpish/shopify_app-skeleton#15]
1.I install composer which is downloaded  from official site.
2.Create a new_prj folder
3.Copy composer.json in new_prj folder.
4.Using command 'php composer.phar install'. After that, a lot of files and one vendor folder are generated.
5.set http://XXXXXX.ngrok.io/new_prj/oauth.php as the Callback URL;
6.open the conf.php file and input API_KEY and SECRET which are copy from shopify parterns
7 visiting http://XXXXXXX.ngrok.io/new_prj/install.php?shop=XXXXX-15.myshopify.com
After step 7, Oauth error invalid_request: The redirect_uri is missing or not whitelisted is showed.
BTW, I add echo $install_url in install.php, and http://XXXXX-15.myshopify.com/admin/api/auth?api_key=*******************************************  appear on the web page several seconds, after, Oauth error invalid_request: The redirect_uri is missing or not whitelisted appear.

What's the problem? TKS

**Comment by myjanky** [comment]
Hi @Mike2100 

see this [https://github.com/phpish/shopify_app-skeleton/issues/9#issuecomment-147216952](url)

**Comment by Mike2100** [comment]
tKS  @myjanky
