### ISSUE TITLE
require __DIR__.'/vendor/autoload.php';

### ISSUE THREAD

**Issue by besoeasy** [phpish/shopify_app-skeleton#29]
Not Found require __DIR__.'/vendor/autoload.php';

**Comment by besoeasy** [comment]
unable to get proper clone of depnd

**Comment by myjanky** [comment]
something is wrong with your composer. Are you using heroku?

**Comment by besoeasy** [comment]
yes using Heroku !  does anyone have more simple version of this app  ?

**Comment by myjanky** [comment]
ohShopify is a little better to setup on heroku.

**Comment by besoeasy** [comment]
thanks ,man works well

**Comment by besoeasy** [comment]
THANKS !
